config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'index' => 'homes#index'
  root 'homes#index'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:show, :edit, :update, :index] do
    get 'follows' => 'relationships#follows'
    get 'followers' => 'relationships#followers'
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200}
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	# Followクラスという存在しないクラスを参照することを防ぎ、User クラスであることを明示しています
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # foregin_key = 入口
  # source = 出口
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    # フォローしようとしている other_user が自分自身ではないかを検証
    unless self == other_user
      # 見つかれば Relation を返し、見つからなければ self.relationships.create(follow_id: other_user.id)
      # としてフォロー関係を保存(create = new + save)することができます。これにより、既にフォローされている場合に
      # フォローが重複して保存されることがなくなります！
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
    
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
    
  end

  def following?(other_user)
    self.followings.include?(other_user)
    
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#name認証
	before_action :configure_permitted_parameters, if: :devise_controller?

	#サインインとサインアップ両方の遷移先
	def after_sign_in_path_for(resource)
 		 user_path(current_user)
	end
	#サインアウト後の遷移先
	def after_sign_out_path_for(resource)
	  	root_path
	end

	protected
	#デフォルト以外のカラムを認証
	def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		#コメントはcomment,book_id,user_idの３つのデータがあるのでそれらが代入するまではcreateされない
		book = Book.find(params[:book_id])
		#comment = PostComment.new(post_comment_params)
		#comment.user_id = current_user.idと下のコードは同じ
		comment = current_user.book_comments.new(book_comment_params) #ここでcommentとuser_idを代入
		comment.book_id = book.id #ここでbook_idを代入

		if comment.save
			flash[:notice] = "Comment was successfully created!"
			redirect_to request.referer
		else
			book_comments = BookComment.where(book_id: book.id)
	      	render '/books/show'
    end
	end
	def destroy
		book_comment = BookComment.find(params[:book_id])
		book_comment.destroy
		redirect_to request.referer
	end
	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  before_action :correct_book, only: [:edit]
  def index
  	@book = Book.new
  	@books = Book.all
  	@user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end


  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		flash[:notice] = "Book was successfully created"
  		redirect_to book_path(@book)
  	else
  		@books = Book.all
  		@user = current_user
  		render :index
  	end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_book
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		#リファラーとは、該当ページに遷移する直前に閲覧されていた参照元（遷移元・リンク元）ページのURLのことrequest.referrerが英語的には正しい
		redirect_to request.referer
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to request.referer
	end
	#リダイレクトの振り分け
	private
	def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to books_pathd
    when 1
      redirect_to book_path(book)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		
	end
	def about
		
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :set_user , only:[:create,:destroy]

	def create
		following = current_user.follow(@user)
		if following.save
			flash[:success] = 'ユーザーをフォローしました。'
			redirect_to request.referer
		else
			flash[:alert] = 'ユーザーのフォローに失敗しました。'
			redirect_to request.referer
		end

	end
	def destroy
		following = current_user.unfollow(@user)
		if following.destroy
			flash[:success] = 'ユーザーのフォローを解除しました。'
			redirect_to request.referer
		else
			flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました。'
			redirect_to request.referer
		end


	end

	def follows
		user = User.find(params[:user_id])
    	@users = user.followings
	end

	def followers
		user = User.find(params[:user_id])
    	@users = user.followers
	end

	private

		def set_user
			@user = User.find(params[:follow_id])
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit]
  def show
  	@user = User.find(params[:id])
  	@users =User.all
  	@book = Book.new
  	@books = @user.books
  end
  def index
  	@book = Book.new
  	@users =User.all
  	@user = current_user
  	
  end
  def edit
  	@user = User.find(params[:id])
  	
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:notice] ="error"
      render :edit
    end
  end
  private 
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  	
  end
  def correct_user
  	user = User.find(params[:id])
  	if user != current_user
  		redirect_to user_path(current_user)
  		flash[:notice] = "error"
  	end
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
  
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %>
<table class="table">
  <tbody>
    <tr>
        <th>name</th>
        <th><%= user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
    </tr>
    <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count ,user_follows_path(user) %></th>
    </tr>
    <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count ,user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>
<div class="row text-center">
 <%= link_to edit_user_path(current_user) do %>
<button class="glyphicon glyphicon-wrench col-xs-12" aria-hidden="true"></button>
 <% end %>
 <hr>
<div class="pull-left">
 <% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id),html:{ method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class:'btn btn-danger' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class:'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>
</div>
</div>


<h2>New book</h2>

<%= form_for(book) do |f| %>
  <%#= render 'devise/shared/error_messages', model: f.object %>
  <div class="field row">
    <h4>Title</h4>
    <%= f.text_field :title, class: "col-xs-12 book_title"%>
  </div>
  <div class="field row">
    <h4>Opinion</h4>

    <%= f.text_area :body, class: "col-xs-12 book_body" %>
    <br>
  </div>
  <div class="actions row">
      <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12"%>
     <br>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<% if @book.errors.any? %>
			 <%= @book.errors.count %>件のerrorが発生しました
			 <%= @book.errors.full_messages.each do |message| %>
			  <%= message %>
			 <% end %>
			<% end %>
			<%= form_for(@book) do |f| %>
			<div class="field row">
				<h4>Title</h4>
				<%= f.text_field :title, class: "col-xs-12 book_title" %>
			</div>
			<div class="field row">
				<h4>Opinion</h4>
				<%= f.text_area :body, class: "col-xs-12 book_body" %>
			</div>
			<div class="actions row">
				<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
			</div>
			<% end %>
			 <%= link_to 'Show', book_path %>
			 <%= link_to 'Back', books_path %>
			 
		</div>
	
	</div>
</div>

app/views/books/index.html.erb
i<div class="container">
  <div class="row">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>件のerrorが発生しました
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
   </div>
  <div class="row">

  <div class="col-xs-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>
    <div class="col-xs-9">
      <h3>Books</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <!--画像やname,titleにlink付けしたい時はdoとendで囲えばいい。 -->
              <!--@booksをbookに格納して、book変数を用いて、book.user_idとすることで、bookを投稿した人のuser_idを取得 -->
              <td><%= link_to user_path(book.user_id) do %>
                <!--bookを投稿したuserを表すのが、book.user -->
                              <%= attachment_image_tag book.user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %>
                  <% end %>

              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
                  <!--いいね機能-->
                    <% if book.favorited_by?(current_user) %>
                        <td>
                            <%= link_to book_favorites_path(book, redirect_id:0), method: :delete do %>
                            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                            <%= book.favorites.count %>
                            <% end %>
                        </td>
                    <% else %>
                        <td>
                            <%= link_to book_favorites_path(book, redirect_id:0), method: :post do %>
                            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                            <%= book.favorites.count %>
                            <% end %>
                        </td>
                    <% end %>
                    <td>
                        <div class="comment">
                                <%= book.book_comments.count %>件コメント
                           
                        </div>
                    </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
© 2020 GitHub, Inc.

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
   <div class="row">
   <div class="col-xs-3">
      <%= render 'books/userinfo', book: @book_new, user: @user %>
    </div>
    <div class="col-xs-9">
    	<h3>Book detail</h3>
    	<table class="table table-striped">
    		<tbody>
    			<tr>
    				<td><%= link_to user_path(@user.id) do %>
                                      <%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %>

    					<%= @user.name %>
    					<% end %>
    				</td>
    				<td><%= link_to book_path(@book.id) do %>
                        <%= @book.title %>
                        <% end %>
                    </td>
    				<td><%= @book.body %></td>
                    <!--いいね機能-->
                    <% if @book.favorited_by?(current_user) %>
                        <td>
                            <%= link_to book_favorites_path(@book,redirect_id:0), method: :delete do %>
                            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                            <%= @book.favorites.count %>
                            <% end %>
                        </td>
                    <% else %>
                        <td>
                            <%= link_to book_favorites_path(@book,redirect_id:0), method: :post do %>
                            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                            <%= @book.favorites.count %>
                            <% end %>
                        </td>
                    <% end %>
                    <td>
                        <div class="comment">
                                <%= @book.book_comments.count %>件コメント
                           
                        </div>
                    </td>
    				<td><% if @book.user_id == current_user.id %>
                        <%= link_to "Edit", edit_book_path(@book.id) ,class:"btn-sm btn-success edit_book_10349" %>
    					<%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" ,class:"btn-sm btn-danger destroy_book_10349" %>
    					<% end %>
    				</td>
    			</tr>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
    		</tbody>
    	</table>
        <!--コメント-->
        <table class="table">
            <% @book.book_comments.each do |book_comment| %>
            <tbody>
                <tr>
                    <td>
                        <%= link_to user_path(book_comment.user) do %>
                          <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
                          <%= book_comment.user.name %>
                        <% end %>
                    </td>
                    <td><%= book_comment.comment %></td>
                    <% if book_comment.user == current_user %>
                        <td><%= link_to "Destroy", book_book_comments_path(book_comment.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn-sm btn-danger" %></td>
                    <% end %>
                </tr>
            </tbody>
            <% end %>
        </table>

        <!--コメント入力フォーム-->
        <%= form_for [@book, @book_comment] do |f| %>
            <div class="row">
                <div class="col-sm-12">
                    <%= f.text_area :comment, rows:'5', class:"form-control",placeholder:"コメントをここに" %>
                </div>
            </div>
            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
        <% end %>
    
    </div>
	</div>
</div>

app/views/favorites/_favorites.html.erb
<% if @book.favorited_by?(current_user) %>
<td>
<%= link_to book_favorites_path(@book), method: :delete do %>
<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
<%= @book.favorites.count %>
<% end %>
</td>
<% else %>
<td>
<%= link_to book_favorites_path(@book), method: :post do %>
<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
<%= @book.favorites.count %>
<% end %>
</td>
<% end %>

app/views/homes/about.html.erb
<h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>

app/views/homes/index.html.erb
<div class='container'>
        <div class="row">
          <div class='top-message col-md-offset-3 col-md-6'>
            <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
            <p>In<span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>,</p>
            <p>you can share and exchange your bodys , inpressions , and emotions</p>
            <p>about varioius books!</p>
            <div class="btn-wrapper">
              <div class="row">
                 <p><<a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
              </div>
            <div class="row">
            <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
            </div>

            </div>
          </div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <br>
    <br>
    <br>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

    <% if user_signed_in? %>
  <body>
      <br>
      <br>
      <br>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nav navbar-left"></nav>
          <nav class="text-muted"><span><strong>Bookers</strong></span></nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Home', user_path(current_user) , class: "glyphicon glyphicon-homes homes"%></li>
              <li><%= link_to 'Users', users_path , class: "glyphicon glyphicon-user users"%></li>
              <li><%= link_to 'Books', books_path , class: "glyphicon glyphicon-book books"%></li>
              <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout"%></li>
            </ul>
          </nav>
        </div>
      </header>
    <% else %>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nav navbar-left"></nav>
          <nav class="text-muted"><span><strong>Bookers</strong></span></nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Home', root_path , class: "glyphicon glyphicon-homes homes"%></li>
              <li><%= link_to 'About', home_about_path , class: "glyphicon glyphicon-link about"%></li>
              <li><%= link_to 'Sign up', new_user_registration_path , class: "glyphicon glyphicon-edit sign_up"%></li>
              <li><%= link_to 'Login',  new_user_session_path, class: "glyphicon glyphicon-log-in sign_in"%></li>
            </ul>
          </nav>
        </div>
      </header>
    <% end %>
    <% if flash[:notice] %>
     <div class="flash">
       <%= flash[:notice] %>
     </div>
    <% end %>
    <main>
       <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
	<% if current_user.following?(user) %>
		<%= form_for(current_user.relationships.find_by(follow_id: user.id),html:{ method: :delete }) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'Unfollow', class:'btn btn-danger' %>
		<% end %>
	<% else %>
		<%= form_for(current_user.relationships.build) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'Follow', class:'btn btn-primary' %>
		<% end %>
	<% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>Followers</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>                    <a><%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %></a>
						</td>
						<td><%= user.name %></td>
						<td><%= render 'relationships/follow_button', user:user  %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/relationships/follows.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>Follows</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>                    <a><%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %></a>
						</td>
						<td><%= user.name %></td>
						<td><%= render 'relationships/follow_button', user:user  %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="col-xs-4">
  
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h2>User info</h2>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label class="control-label" for="inputEmail">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
        <div class="form-group has-icon">
    <label class="control-label" for="inputEmail">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>
	<label class="control-label" for="inputEmail">introduction</label>
        <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>
    <%= f.submit "Update User", class:"btn btn-primary btn-block " %>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'books/userinfo', book: @book, user: @user %>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>                    <a><%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %></a>
						</td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>.
    <div class="col-xs-9">
      <h3>Books</h3>
      <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
               <%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thubm" , fallback: "no_image.jpg", size: "60x60" %>
              <% end %>
            <td>
              <%= link_to book.title, book_path(book) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>